name: CI/CD for Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and run Flask app
      run: |
        python app.py &

    - name: Wait for the app to start
      run: sleep 3

    - name: Run tests (optional)
      run: |
        # Add your test commands here

    - name: Stop Flask app
      run: kill $(jobs -p) || true
